name: Deploy

permissions:
  id-token: write
  contents: read

on: 
  workflow_dispatch:
    inputs:
      appenv:
        type: choice
        description: Choose the target environment
        default: dev
        options: 
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          client-id: 5dd2cbbc-474c-43f4-adf0-2d510a8da283
          tenant-id: 6988ef53-709f-417d-bde1-e21c24244485
          subscription-id: ad582931-4bbe-4158-b97f-5c70027069be
          enable-AzPSSession: true
      - name: Run Bicep deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ad582931-4bbe-4158-b97f-5c70027069be
          resourceGroupName: DevProductivityWorkshop
          template: ./InfrastructureAsCode/main.bicep
          parameters: environment= dev